# Generated by Django 3.2.6 on 2021-09-30 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy_django_dashboard', '0002_auto_20210907_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestpagetype',
            name='scraper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scrapy_django_dashboard.scraper'),
        ),
        migrations.AlterField(
            model_name='scraperelem',
            name='scraper',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='scrapy_django_dashboard.scraper'),
        ),
    ]
