# Generated by Django 3.2.6 on 2021-08-21 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('university', models.CharField(max_length=60)),
                ('universityRanking', models.DecimalField(decimal_places=0, max_digits=4)),
                ('fees', models.DecimalField(decimal_places=2, default='0', max_digits=8)),
                ('atar', models.DecimalField(decimal_places=2, max_digits=4)),
                ('years', models.DecimalField(decimal_places=0, max_digits=2)),
                ('creditPoints', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
