# Generated by Django 3.2.6 on 2021-08-21 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0003_alter_course_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='creditPoints',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
