# Generated by Django 3.2.6 on 2021-08-21 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0004_alter_course_creditpoints'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='creditPoints',
            field=models.DecimalField(decimal_places=0, max_digits=3),
        ),
    ]
