# Generated by Django 3.2.6 on 2021-08-24 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0013_auto_20210824_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='courseLink',
            field=models.CharField(default='course link', max_length=150),
        ),
    ]
