# Generated by Django 3.2.6 on 2021-09-08 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrapy_django_dashboard', '0002_auto_20210907_1525'),
        ('myapi', '0014_course_courselink'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='courseLink',
        ),
        migrations.AddField(
            model_name='course',
            name='checker_runtime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scrapy_django_dashboard.schedulerruntime'),
        ),
        migrations.AddField(
            model_name='course',
            name='url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='learningOutcomes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='CourseWebsite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('url', models.URLField()),
                ('scraper', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scrapy_django_dashboard.scraper')),
                ('scraper_runtime', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='scrapy_django_dashboard.schedulerruntime')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='course_website',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='myapi.coursewebsite'),
        ),
    ]
