# Generated by Django 3.2.6 on 2021-09-08 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0015_auto_20210908_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='url',
            new_name='courseLink',
        ),
    ]
