# Generated by Django 3.2.6 on 2021-09-08 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0016_rename_url_course_courselink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='courseLink',
            new_name='url',
        ),
    ]
