# Generated by Django 3.2.6 on 2021-09-08 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0017_rename_courselink_course_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='url',
            new_name='courseLink',
        ),
    ]
