# Generated by Django 3.2.6 on 2021-09-08 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0020_rename_url_course_courselink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursewebsite',
            old_name='name',
            new_name='title',
        ),
    ]
