# Generated by Django 3.2.6 on 2021-09-08 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0021_rename_name_coursewebsite_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursewebsite',
            old_name='title',
            new_name='name',
        ),
        migrations.AddField(
            model_name='course',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
