# Generated by Django 3.2.6 on 2021-09-08 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0022_auto_20210908_1431'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coursewebsite',
            old_name='name',
            new_name='title',
        ),
    ]
