# Generated by Django 3.2.6 on 2021-09-08 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0023_rename_name_coursewebsite_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='courseLink',
        ),
    ]
