# Generated by Django 3.2.6 on 2021-09-08 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0024_remove_course_courselink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='name',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='coursewebsite',
            old_name='title',
            new_name='name',
        ),
    ]
