# Generated by Django 3.2.6 on 2021-09-20 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0025_auto_20210908_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='universityRanking',
        ),
    ]
