# Generated by Django 3.2.6 on 2021-09-20 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0026_remove_course_universityranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='university',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
