# Generated by Django 3.2.6 on 2021-09-25 07:52

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0027_alter_course_university'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='dateScraped',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
