# Generated by Django 3.2.6 on 2021-09-25 08:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0028_course_datescraped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='dateScraped',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
