# Generated by Django 3.2.6 on 2021-09-25 08:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0029_alter_course_datescraped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='dateScraped',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
