# Generated by Django 3.2.6 on 2021-09-26 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0031_alter_course_datescraped'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='state',
            field=models.CharField(choices=[('NSW', 'New South Wales'), ('NT', 'Northern Territory'), ('QLD', 'Queensland'), ('SA', 'South Australia'), ('TAS', 'Tasmania'), ('VIC', 'Victoria'), ('WA', 'Western Australia')], default='VIC', max_length=3),
        ),
    ]
