# Generated by Django 3.2.6 on 2021-09-26 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0032_course_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='campus',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
