# Generated by Django 3.2.6 on 2021-09-29 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0033_course_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='yearlyFees',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=8),
        ),
        migrations.AlterField(
            model_name='course',
            name='fees',
            field=models.DecimalField(blank=True, decimal_places=2, default='0', max_digits=8),
        ),
    ]
