# Generated by Django 3.2.6 on 2021-09-29 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0034_auto_20210929_1102'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='dateScraped',
            new_name='dateTimeScraped',
        ),
    ]
