# Generated by Django 3.2.6 on 2021-09-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0035_rename_datescraped_course_datetimescraped'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='yearlyFees',
            field=models.TextField(blank=True),
        ),
    ]
