# Generated by Django 3.2.6 on 2021-09-30 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0037_alter_course_yearlyfees'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='requiredAtar',
            new_name='guaranteedAtar',
        ),
    ]
