# Generated by Django 3.2.6 on 2021-09-30 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0038_rename_requiredatar_course_guaranteedatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='idUrl',
            field=models.URLField(blank=True),
        ),
    ]
