# Generated by Django 3.2.6 on 2021-10-05 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0039_course_idurl'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='creditPoints',
            new_name='units',
        ),
    ]
