# Generated by Django 3.2.6 on 2021-10-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0040_rename_creditpoints_course_units'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='uniRanking',
            field=models.DecimalField(decimal_places=2, default='69', max_digits=5),
        ),
        migrations.AlterField(
            model_name='course',
            name='state',
            field=models.CharField(choices=[('NSW', 'New South Wales'), ('NT', 'Northern Territory'), ('QLD', 'Queensland'), ('SA', 'South Australia'), ('TAS', 'Tasmania'), ('VIC', 'Victoria'), ('WA', 'Western Australia'), ('ACT', 'Australian Capital Territory')], default='VIC', max_length=3),
        ),
        migrations.AlterField(
            model_name='course',
            name='units',
            field=models.DecimalField(decimal_places=2, default='24', max_digits=5),
        ),
    ]
