# Generated by Django 3.2.6 on 2021-10-20 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0041_auto_20211020_0840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='uniRanking',
            field=models.DecimalField(decimal_places=2, default='69', max_digits=8),
        ),
    ]
