# Generated by Django 3.2.6 on 2021-10-20 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0042_alter_course_uniranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='state',
            field=models.CharField(choices=[('New South Wales', 'New South Wales'), ('Northern Territory', 'Northern Territory'), ('Queensland', 'Queensland'), ('South Australia', 'South Australia'), ('Tasmania', 'Tasmania'), ('Victoria', 'Victoria'), ('Western Australia', 'Western Australia'), ('Australian Capital Territory', 'Australian Capital Territory')], default='Victoria', max_length=30),
        ),
    ]
