# Generated by Django 3.2.6 on 2021-10-21 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapi', '0049_alter_course_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='guaranteedAtar',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4),
        ),
    ]
